version: '3.7'

services:

  db:
    image: postgres:14
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: windmill

  windmill_server:
    image: ghcr.io/windmill-labs/windmill:main
    deploy:
      replicas: 1
    restart: always
    ports:
      - 172.17.0.1:8496:8000
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db/windmill?sslmode=disable
      - BASE_URL=https://${BASE_URL}
      - RUST_LOG=info
      ## You can set the number of workers to > 0 and not need any separate worker service
      - NUM_WORKERS=0
      - DISABLE_SERVER=false
      - METRICS_ADDR=false

  windmill_worker:
    image: ghcr.io/windmill-labs/windmill:main
    deploy:
      replicas: 3
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db/windmill?sslmode=disable
      - BASE_URL=https://${BASE_URL}
      - BASE_INTERNAL_URL=http://windmill_server:8000
      - RUST_LOG=info
      - NUM_WORKERS=1
      - DISABLE_SERVER=true
      - KEEP_JOB_DIR=false
      - DENO_PATH=/usr/bin/deno
      - PYTHON_PATH=/usr/local/bin/python3
      - METRICS_ADDR=false
    # to mount the worker folder to debug,, KEEP_JOB_DIR=true and mount /tmp/windmill
    volumes:
      - ./worker_dependency_cache:/tmp/windmill/cache
      # - ./oauth.json/:/usr/src/app/oauth.json

  lsp:
    image: ghcr.io/windmill-labs/windmill-lsp:latest
    restart: always
    ports:
      - 172.17.0.1:3001:3001

  caddy:
    image: caddy:2.5.2-alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 172.17.0.1:4580:80
      # - 172.17.0.1:4443:443
    environment:
      - BASE_URL=${BASE_URL}

volumes:
  db_data: null
  worker_dependency_cache: null
